# Generated by Django 3.0.3 on 2020-06-13 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('bpm', models.IntegerField()),
                ('mp3_price', models.FloatField()),
                ('price', models.FloatField()),
                ('wav_price', models.FloatField()),
                ('key', models.CharField(max_length=7)),
                ('tags', models.CharField(max_length=256, null=True)),
                ('in_cart', models.BooleanField(default=False)),
                ('track_status', models.CharField(default='not-clicked', max_length=15)),
                ('selected_type', models.CharField(default='mp3', max_length=7)),
                ('sample_audio', models.FileField(upload_to='media/sample_audio')),
                ('mp3', models.FileField(upload_to='media/mp3')),
                ('wav', models.FileField(upload_to='media/wav')),
                ('artwork', models.FileField(upload_to='media/artwork')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
