# Generated by Django 3.0.3 on 2020-05-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='price',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='key',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_status',
            field=models.CharField(default='not-clicked', max_length=20),
        ),
    ]
