# Generated by Django 3.0.3 on 2020-05-11 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20200502_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
