# Generated by Django 3.0.3 on 2020-06-03 17:54

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_auto_20200511_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artwork',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='mp3',
            field=s3direct.fields.S3DirectField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='sample_audio',
            field=s3direct.fields.S3DirectField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='wav',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
