# Generated by Django 3.0.3 on 2020-06-03 18:18

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_auto_20200603_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='mp3',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='sample_audio',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='wav',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
