# Generated by Django 3.0.3 on 2020-05-22 08:52

from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
