# Generated by Django 3.0.3 on 2020-05-22 09:13

from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0002_auto_20200522_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150)),
                ('items', jsonfield.fields.JSONField()),
                ('prices', jsonfield.fields.JSONField()),
                ('types', jsonfield.fields.JSONField()),
                ('links', models.TextField()),
                ('total', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
